### ISSUE TITLE
Old tweets throwing error

### ISSUE THREAD

**Issue by bobbysteel** [MikeMcQuaid/TwitterDelete#9] opened 2017-02-27 00:12 UTC
I'm getting odd errors, presumably from old Tweets the API isn't returning.
```
/usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:15:in `on_complete': No status found with that ID. (Twitter::Error::NotFound)
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/request/multipart_with_file.rb:17:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:33:in `perform'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:51:in `perform_request'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:73:in `perform_request_with_object'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:151:in `block in parallel_objects_from_response'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/utils.rb:39:in `block (2 levels) in pmap'
```
As a fix (and as a feature I like) I also added a parameter to not delete my oldest tweets (as I like having the very old ones there just to brag my account is in the first handful of ones created)
https://github.com/bobbysteel/TwitterDelete/blob/master/twitter_delete.rb

**Comment by MikeMcQuaid** [comment] 2017-02-27 08:16
Do you have a more complete backtrace? This doesn't seem to list any of my code so it's hard to figure out.

This may need a fix similar to https://github.com/MikeMcQuaid/TwitterDelete/pull/8.

**Comment by bobbysteel** [comment] 2017-02-27 08:17
How can I get a backtrace? I'm not terribly familiar w Ruby unfortunately

**Comment by MikeMcQuaid** [comment] 2017-02-27 08:19
Can you paste the entire output of the command? Thanks!

**Comment by bobbysteel** [comment] 2017-02-27 08:19
Ah reading #8 I suspect you're right. That said it's useful to have a limit
how far to go back as well :)

**Comment by bobbysteel** [comment] 2017-02-27 08:20
Yes but need to wait a while until in front of a pc so I can pull out all
personally identifiable data...

**Comment by MikeMcQuaid** [comment] 2017-02-27 08:23
Sure, no rush.

**Comment by bobbysteel** [comment] 2017-02-27 10:48
```
==> Checking favourites...
Checking timeline...
Ignoring tweet: too favourited: xxxx
Ignoring tweet: too favourited: xxx
Ignoring tweet: too favourited: xxx
Ignoring tweet: too favourited: xxx
Ignoring tweet: too RTd: xxx
Ignoring tweet: too favourited: xxx
Ignoring tweet: too favourited: xxx
Ignoring tweet: too favourited: xxx
Ignoring tweet: too favourited: xxx
Ignoring tweet: too RTd: xxx
==> Unfavoriting 2 tweets
/usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/response/rai                                                       se_error.rb:15:in `on_complete': No status found with that ID. (Twitter::Error::                                                       NotFound)
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/respo                                                       nse.rb:9:in `block in call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/respo                                                       nse.rb:57:in `on_complete'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/respo                                                       nse.rb:8:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/reque                                                       st/url_encoded.rb:15:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/reque                                                       st/multipart.rb:14:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest                                                       /request/multipart_with_file.rb:17:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/rack_                                                       builder.rb:139:in `build_response'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/conne                                                       ction.rb:377:in `run_request'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/conne                                                       ction.rb:177:in `post'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest                                                       /request.rb:33:in `perform'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest                                                       /utils.rb:51:in `perform_request'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest                                                       /utils.rb:73:in `perform_request_with_object'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest                                                       /utils.rb:151:in `block in parallel_objects_from_response'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/util                                                       s.rb:39:in `block (2 levels) in pmap'
```

**Comment by MikeMcQuaid** [comment] 2017-03-03 13:20
As I can't reproduce gonna consider https://github.com/MikeMcQuaid/TwitterDelete/pull/10 as a fix for this. Thanks!

**Closed** 2017-03-03 13:20 UTC

**Comment by bobbysteel** [comment] 2018-04-23 10:52
Fwiw this is still happening. Error text has changed a bit. For example, I can run and two days later, run again so tweets say 12-14 days old are the ones to be deleted:

```
==> Unfavoriting 34 tweets
==> Deleting 10 tweets
/usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:13:in `on_complete': You may not delete another user's status. (Twitter::Error::Forbidden)
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/request/multipart_with_file.rb:17:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:33:in `perform'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:51:in `perform_request'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:73:in `perform_request_with_object'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:65:in `perform_post_with_object'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/tweets.rb:100:in `block in destroy_status'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/utils.rb:37:in `block in pmap'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/utils.rb:37:in `collect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/utils.rb:37:in `pmap'
        from /usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.14.0/lib/twitter/rest/tweets.rb:99:in `destroy_status'
        from twitter_delete.rb:71:in `api_call'
        from twitter_delete.rb:141:in `block in <main>'
        from twitter_delete.rb:139:in `each'
        from twitter_delete.rb:139:in `<main>'
```

**Comment by MikeMcQuaid** [comment] 2018-04-23 16:01
@bobbysteel I can't reproduce this so there's nothing I can do on my end. If you submit a PR that fixes this issue I'll consider accepting it.
